### ISSUE TITLE
.

### ISSUE THREAD

**Issue by SarnaxLii** [lujiangz/trixware#3]
.

**Comment by lujiangz** [comment]
I don't think so, it hasn't been updated for a long time and I think it would make more sense to use the original version instead of using this

**Comment by Speedyreal** [comment]
thanks

**Comment by Santiagocostaa** [comment]
Help guys [SarnaxLii](https://github.com/SarnaxLii) He is a scammer , he robbed me , I paid for a spoofer he deleted everything after receiving the money , waited 1 day and deleted me

**Comment by SarnaxLii** [comment]
@Santiagocostaa Show me proof when I cheated on you idiot. Your account was created a day or two ago, that's funny.

**Comment by Ovutuleu92** [comment]
> @Santiagocostaa Show me proof when I cheated on you idiot. Your account was created a day or two ago, that's funny.

Nice scam you broke Thailand retard.
I reported your shit to DMCA, Github, and Discord server.
imagine scamming for 35 USD.
you scammed @santiagocostaa and me.

**Comment by Ovutuleu92** [comment]
i will show you proof, no problem

**Comment by Ovutuleu92** [comment]
[](https://imgur.com/a/kw4zVoV)

**Comment by Ovutuleu92** [comment]
https://imgur.com/a/kw4zVoV

**Comment by Ovutuleu92** [comment]
NICE SCAMMMMM FOR 35 USD HAAHAHHA

**Comment by SarnaxLii** [comment]
It's funny how you signed up for a new account to humiliate me. But I don't care and don't give you a price.

**Comment by SarnaxLii** [comment]
Your account was created less than a day ago, most funny trying to make me look bad.

**Comment by Ovutuleu92** [comment]
Funny thing is i can literally make a video, whole chat showing your real Discord ID. Don't worry buddy, i don't have to make you look bad. Say bye bye to your Cheating discord, its the question of time when it will get banned by Discord for Violating TOS. I will make sure your Github will go down aswell..

Again, i can provide all the proof showing me paying you, talking to you, as i took pictures when i've sent you the BTC.

**Comment by Ovutuleu92** [comment]
Wayback machine also shows you literally took down your discord server invite link after you scammed me. And you keep deleting every comment. The odds are against you here buddy. You will drink blood for that 35 USD you scammed me.

**Comment by SarnaxLii** [comment]
don't intimidate me because I'm not afraid of you I have a lot of servers lmao please show me the proof

**Comment by SarnaxLii** [comment]
Intimidating me doesn't help. because I didn't give you a lot of prices.

**Comment by Ovutuleu92** [comment]
Show you proof? you are the one who literally scammed me, i will show proof to the public tho. I dont have to intimidate you. You will see for yourself.

**Comment by Ovutuleu92** [comment]
> Intimidating me doesn't help. because I didn't give you a lot of prices.

I am not intimidating you. I will show you what is in my power :) As i said, enjoy the 35 USD buddy.

**Comment by SarnaxLii** [comment]
I'm waiting and proof that I deceived My server doesn't break any rules, of course, even if it's disabled, I have multiple servers. I don't care about you

**Comment by Ovutuleu92** [comment]
> I'm waiting and proof that I deceived My server doesn't break any rules, of course, even if it's disabled, I have multiple servers. I don't care about you

what you said, clearly shows how dumb you are. Your discord server wich involves HACK SELLING, breaks Discord Terms of Usage. It takes me a few reports to ban YOU, and your discord server. Consider that done. I will do everything in my power to take your github aswell.

**Comment by SarnaxLii** [comment]
I give you 1 month to deactivate my server. Hope it works xD

**Comment by Ovutuleu92** [comment]
I already filed numerous reports to Discord, including phonecalling them to talk to a representative. Hacks on discord, especially selling is against their TOS. You will see sooner or later. I personally Called github aswell, to file a report with you scamming peoeple left and right. Imagine how desperate you gotta be to scam 35 USD mate. 35 USD lmfao

**Comment by SarnaxLii** [comment]
I do not know you and I don't know who you are you're accusing me the funniest lmao

**Comment by SarnaxLii** [comment]
hahahhahaaaha ok im waiting

**Comment by Ovutuleu92** [comment]
You fucking thailand broke cunt dog. Go eat a fucking bat or a dog you fucking broke monkey.

**Comment by SarnaxLii** [comment]
@Ovutuleu92 Toxic doesn't help at all :)

**Comment by lujiangz** [comment]
if you really have no proof i will delete this thing

**Comment by SarnaxLii** [comment]
@lujiangz Close I'm broken. I gave him 2 days time but no update.

**Comment by SarnaxLii** [comment]
Delete this question and I'm going to discuss it on his new question. Let's show our strength

**Comment by lujiangz** [comment]
our strength? I only talked to you about a project. Later, my friend said that you are a scammer and he saw it somewhere idk where. Other than that, I don't really care what you do, I'm just trying to improve myself here. When you share a project tomorrow, of course I will deal with it and examine them.

**Comment by lujiangz** [comment]
and I don't understand why you are discussing in this project's issues section xd

**Comment by SarnaxLii** [comment]
Remove my question from your problem. If it bothers you too much

thank you
